services:
  bot:
    container_name: "helper_bot"
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    env_file: stack.env
    deploy:
      resources:
        limits:
          memory: 500M
